services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    restart: always
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # Enables the web UI and tells Traefik to listen to docker
    command: 
    - --providers.docker
    - --providers.docker.exposedbydefault=false
    - --entrypoints.http.address=:80
    - --api.insecure=true 
    - --accesslog
    - --log

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true